title: Nicholas Brown
theme: jekyll-theme-slate
author: Java/C++ Coder
email: NickBProgramming@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my resume! If your interested or have any questions, please let me know!

# social links
twitter_username: your-twitter-handle
github_username:  NickBProgramming

show_excerpts: false # set to false to remove excerpts on the homepage
